no not localize sites
apostrophecms/content-upgrader pull request #9
Opened 2022-11-17 14:56 UTC by ETLaurent

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-11-29 08:36 UTC, ETLaurent commented on CHANGELOG.md
> +
ℹ️ already released (under the `beta` tag)

2022-12-06 21:35 UTC, boutell requested changes

2022-12-06 21:35 UTC, boutell commented on index.js
> +      // TODO: check if multisite?
Missing the check.

2022-12-06 21:35 UTC, boutell commented on index.js
> +      // TODO: check if multisite?
Check for `apos.options.multisite` which is only present in a multisite project.

2022-12-07 12:43 UTC, boutell approved these changes

2022-12-07 12:43 UTC, boutell commented
OK to merge and publish as the next beta

2022-12-07 13:13 UTC, merged